[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2018"
authors = ["T Kumagai <s8zmnonun@relay.firefox.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1.27"
